/** AUTO-GENERATED — 生产构建占位，勿手动编辑。生成：npm run generate:mock-stubs */
/* eslint-disable @typescript-eslint/no-explicit-any */

export const MOCK_STUDENTS: unknown[] = [];
export const MOCK_PACKAGES: unknown[] = [];
export const MOCK_CLASSES: unknown[] = [];
export async function mockGetStudents(..._args: any[]): Promise<any> { return null; }
export async function mockGetStudentById(..._args: any[]): Promise<any> { return null; }
export async function mockGetStudentPackages(..._args: any[]): Promise<any> { return null; }
export async function mockGetClasses(..._args: any[]): Promise<any> { return null; }
export async function mockGetClassById(..._args: any[]): Promise<any> { return null; }
export async function mockGetClassStudents(..._args: any[]): Promise<any> { return null; }
export async function mockGetLessonRecords(..._args: any[]): Promise<any> { return null; }
export async function mockGetLeaveRequests(..._args: any[]): Promise<any> { return null; }
export async function mockGetTeachers(..._args: any[]): Promise<any> { return null; }
export async function mockGetTeacherById(..._args: any[]): Promise<any> { return null; }
export async function mockGetSubjects(..._args: any[]): Promise<any> { return null; }
export async function mockGetCampusList(..._args: any[]): Promise<any> { return null; }
export async function mockGetScheduleByClassId(..._args: any[]): Promise<any> { return null; }
export async function mockGetScheduleByTeacherId(..._args: any[]): Promise<any> { return null; }
export async function mockCreateSchedule(..._args: any[]): Promise<any> { return null; }
export async function mockUpdateSchedule(..._args: any[]): Promise<any> { return null; }
export async function mockDeleteSchedule(..._args: any[]): Promise<any> { return null; }
export async function mockCheckScheduleConflict(..._args: any[]): Promise<any> { return null; }
export async function mockGetNotificationsByReceiver(..._args: any[]): Promise<any> { return null; }
export async function mockMarkNotificationAsRead(..._args: any[]): Promise<any> { return null; }
export async function mockMarkAllNotificationsAsRead(..._args: any[]): Promise<any> { return null; }
export async function mockSendNotification(..._args: any[]): Promise<any> { return null; }
export async function mockGetStudentsByTeacher(..._args: any[]): Promise<any> { return null; }
export async function mockSearchStudents(..._args: any[]): Promise<any> { return null; }
export async function mockGetStudentsByParent(..._args: any[]): Promise<any> { return null; }
export async function mockCreateStudent(..._args: any[]): Promise<any> { return null; }
export async function mockUpdateStudent(..._args: any[]): Promise<any> { return null; }
export async function mockDeleteStudent(..._args: any[]): Promise<any> { return null; }
export async function mockGetStudentDependencies(..._args: any[]): Promise<any> { return null; }
export async function mockCheckDuplicateName(..._args: any[]): Promise<any> { return null; }
export async function mockGetParentsByStudent(..._args: any[]): Promise<any> { return null; }
export async function mockRemoveParentFromStudent(..._args: any[]): Promise<any> { return null; }
export async function mockFindStudentByInviteCode(..._args: any[]): Promise<any> { return null; }
export async function mockBindParentToStudent(..._args: any[]): Promise<any> { return null; }
export async function mockGetPackagesByStudent(..._args: any[]): Promise<any> { return null; }
export async function mockGetPackageById(..._args: any[]): Promise<any> { return null; }
export async function mockCreatePackage(..._args: any[]): Promise<any> { return null; }
export async function mockUpdatePackage(..._args: any[]): Promise<any> { return null; }
export async function mockDeductPackageHours(..._args: any[]): Promise<any> { return null; }
export async function mockGetActivePackagesByStudent(..._args: any[]): Promise<any> { return null; }
export async function mockGetPackageTemplates(..._args: any[]): Promise<any> { return null; }
export async function mockCreatePackageTemplate(..._args: any[]): Promise<any> { return null; }
export async function mockUpdatePackageTemplate(..._args: any[]): Promise<any> { return null; }
export async function mockDeletePackageTemplate(..._args: any[]): Promise<any> { return null; }
export async function mockGetRecordsByStudent(..._args: any[]): Promise<any> { return null; }
export async function mockGetLessonRecordsByTeacher(..._args: any[]): Promise<any> { return null; }
export async function mockGetLessonRecordsByTeacherAndMonth(..._args: any[]): Promise<any> { return null; }
export async function mockGetLessonRecordsByTeacherAndRange(..._args: any[]): Promise<any> { return null; }
export async function mockGetLessonRecordsByStudent(..._args: any[]): Promise<any> { return null; }
export async function mockGetAllLessonRecords(..._args: any[]): Promise<any> { return null; }
export async function mockCreateLessonRecord(..._args: any[]): Promise<any> { return null; }
export async function mockRevokeLessonRecord(..._args: any[]): Promise<any> { return null; }
export async function mockGetLessonRecordById(..._args: any[]): Promise<any> { return null; }
export async function mockDeleteLessonRecord(..._args: any[]): Promise<any> { return null; }
export async function mockUpdateLessonRecord(..._args: any[]): Promise<any> { return null; }
export async function mockGetLeavesByStudent(..._args: any[]): Promise<any> { return null; }
export async function mockGetLeavesByTeacher(..._args: any[]): Promise<any> { return null; }
export async function mockCreateLeaveRequest(..._args: any[]): Promise<any> { return null; }
export async function mockUpdateLeaveRequestStatus(..._args: any[]): Promise<any> { return null; }
export async function mockGetClassesByTeacher(..._args: any[]): Promise<any> { return null; }
export async function mockGetStudentsByClass(..._args: any[]): Promise<any> { return null; }
export async function mockGetClassStudentCount(..._args: any[]): Promise<any> { return null; }
export async function mockCreateClass(..._args: any[]): Promise<any> { return null; }
export async function mockUpdateClass(..._args: any[]): Promise<any> { return null; }
export async function mockDeleteClass(..._args: any[]): Promise<any> { return null; }
export async function mockRemoveStudentFromClass(..._args: any[]): Promise<any> { return null; }
export async function mockAddStudentsToClass(..._args: any[]): Promise<any> { return null; }
export async function mockTransferStudent(..._args: any[]): Promise<any> { return null; }
export async function mockEndClass(..._args: any[]): Promise<any> { return null; }
export async function mockGetSchedulesByTeacher(..._args: any[]): Promise<any> { return null; }
export async function mockGetScheduleById(..._args: any[]): Promise<any> { return null; }
export async function mockCreateScheduleFull(..._args: any[]): Promise<any> { return null; }
export async function mockUpdateScheduleFull(..._args: any[]): Promise<any> { return null; }
export async function mockDeleteScheduleFull(..._args: any[]): Promise<any> { return null; }
export async function mockCreateRecharge(..._args: any[]): Promise<any> { return null; }
export async function mockGetRechargeRecords(..._args: any[]): Promise<any> { return null; }
export async function mockCreateRefund(..._args: any[]): Promise<any> { return null; }
export async function mockGetPackageTransactions(..._args: any[]): Promise<any> { return null; }
export async function mockGetSchedulesByStudent(..._args: any[]): Promise<any> { return null; }
export async function getActorScope(..._args: any[]): Promise<any> { return null; }
export async function filterStudentsByActor(..._args: any[]): Promise<any> { return null; }
export async function filterClassesByActor(..._args: any[]): Promise<any> { return null; }
export async function filterSchedulesByActor(..._args: any[]): Promise<any> { return null; }
export async function resolveMyTeacherIds(..._args: any[]): Promise<any> { return null; }
export async function resolveMyTeachingActorIds(..._args: any[]): Promise<any> { return null; }
export async function isMyTeachingSchedule(..._args: any[]): Promise<any> { return null; }
export async function filterSchedulesForMyToday(..._args: any[]): Promise<any> { return null; }
export async function filterLessonRecordsByActor(..._args: any[]): Promise<any> { return null; }
export async function filterPackagesByActor(..._args: any[]): Promise<any> { return null; }
export async function formatDateCN(..._args: any[]): Promise<any> { return null; }
export async function pickBestPackage(..._args: any[]): Promise<any> { return null; }
