export default defineAppConfig({
  pages: [
    'pages/home/index',
    'pages/schedule/index',
    'pages/booking/index',
    'pages/index/index',
    'pages/login/index',
    'pages/login/forgot-account/index',
    'pages/login/forgot-password/index',
    'pages/login/contact-support/index',
    'pages/register/index',
    'pages/register/role-select',
    'pages/register/role-info',
    'pages/role-switch/index',
    'pages/role-switch/add-role',
    'pages/statistics/index',
    'pages/profile/index',
    'pages/notifications/index',
    'pages/agreement/index',
  ],
  subPackages: [
    {
      root: 'package-student',
      pages: [
        'pages/students/index',
        'pages/student-detail/index',
        'pages/student-form/index',
        'pages/student-transfer/index',
        'pages/parent-bind/index',
      ],
    },
    {
      root: 'package-teacher',
      pages: [
        'pages/teacher-list/index',
        'pages/teacher-detail/index',
        'pages/salary-detail/index',
        'pages/attendance/index',
      ],
    },
    {
      root: 'package-course',
      pages: [
        'pages/classes/index',
        'pages/class-detail/index',
        'pages/class-form/index',
        'pages/class-checkin/index',
        'pages/course-packages/index',
        'pages/package-form/index',
        'pages/lesson-form/index',
        'pages/lesson-edit/index',
        'pages/lesson-supplement/index',
        'pages/lesson-detail/index',
        'pages/schedule-form/index',
        'pages/booking-rule/index',
        'pages/teacher-booking-config/index',
        'pages/booking-record-detail/index',
        'pages/batch-reschedule-select/index',
        'pages/batch-reschedule-confirm/index',
        'pages/records/index',
        'pages/recharge-records/index',
        'pages/leave-request/index',
      ],
    },
    {
      root: 'package-settings',
      pages: [
        'pages/campus-settings/index',
        'pages/campus-settings/sub-campus',
        'pages/campus-settings/pay-day',
        'pages/campus-settings/holidays',
        'pages/campus-settings/subjects',
        'pages/campus-settings/notify',
        'pages/campus-settings/campus-data/index',
        'pages/system-settings/index',
        'pages/feedback/index',
        'pages/notification-send/index',
      ],
    },
    {
      root: 'package-statistics',
      pages: ['pages/alert-detail/index'],
    },
    {
      root: 'package-lead',
      pages: [
        'pages/my-invite/index',
        'pages/lead-form/index',
        'pages/lead-detail/index',
        'pages/trial-booking/index',
        'pages/proxy-booking-form/index',
        'pages/proxy-member-select/index',
        'pages/trial-slots/index',
        'pages/trial-slot-config/index',
        'pages/lead-booking-detail/index',
        'pages/lead-booking-edit/index',
        'pages/open-slot-edit/index',
        'pages/class-slot-config/index',
        'pages/invite-qrcode/index',
        'pages/invite-landing/index',
      ],
    },
  ],
  /** 进入课表页后预下载 package-lead 分包，加速「排课/预约」Tab 切换 */
  preloadRule: {
    'pages/schedule/index': {
      packages: ['package-lead'],
      network: 'all',
    },
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#3B6EF5',
    navigationBarTitleText: '松果排课',
    navigationBarTextStyle: 'white',
  },
  tabBar: {
    color: '#999999',
    selectedColor: '#3B6EF5',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
        iconPath: 'assets/icons/home_unselected.png',
        selectedIconPath: 'assets/icons/home_selected.png',
      },
      {
        pagePath: 'pages/schedule/index',
        text: '课表',
        iconPath: 'assets/icons/schedule_unselected.png',
        selectedIconPath: 'assets/icons/schedule_selected.png',
      },
      {
        pagePath: 'pages/statistics/index',
        text: '统计',
        iconPath: 'assets/icons/checkin_unselected.png',
        selectedIconPath: 'assets/icons/checkin_selected.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/icons/profile_unselected.png',
        selectedIconPath: 'assets/icons/profile_selected.png',
      },
    ],
  },
});
