export default defineAppConfig({
  pages: [
    'pages/home/index',
    'pages/schedule/index',
    'pages/booking/index',
    'pages/my-course/index',
    'pages/venue-booking/index',
    'pages/index/index',
    'pages/login/index',
    'pages/login/forgot-account/index',
    'pages/login/forgot-password/index',
    'pages/login/contact-support/index',
    'pages/register/index',
    'pages/register/role-select',
    'pages/register/role-info',
    'pages/role-switch/index',
    'pages/role-switch/add-role',
    'pages/statistics/index',
    'pages/finance-data/index',
    'pages/member-data/index',
    'pages/card-data/index',
    'pages/salary-data/index',
    'pages/record-transaction/index',
    'pages/profile/index',
    'pages/profile-edit/index',
    'pages/child-detail/index',
    'pages/children/index',
    'pages/notifications/index',
    'pages/agreement/index',
    'pages/about/index',
    'pages/store-entry/index',
  ],
  subPackages: [
    {
      root: 'package-student',
      pages: [
        'pages/students/index',
        'pages/student-detail/index',
        'pages/student-form/index',
        'pages/student-transfer/index',
        'pages/parent-bind/index',
        'pages/member-card-issue/index',
        'pages/member-card-detail/index',
        'pages/member-card-edit/index',
        'pages/follow-record-form/index',
        'pages/help/index',
      ],
    },
    {
      root: 'package-teacher',
      pages: [
        'pages/teacher-list/index',
        'pages/teacher-form/index',
        'pages/teacher-detail/index',
        'pages/salary-detail/index',
        'pages/salary-adjust/index',
        'pages/attendance/index',
        'pages/salary-home/index',
        'pages/salary-payment/index',
        'pages/salary-settings/index',
        'pages/salary-form/index',
        'pages/salary-template/index',
        'pages/salary-template-form/index',
      ],
    },
    {
      root: 'package-course',
      pages: [
        'pages/classes/index',
        'pages/class-detail/index',
        'pages/class-form/index',
        'pages/class-checkin/index',
        'pages/course-management/index',
        'pages/subject-management/index',
        'pages/subject-form/index',
        'pages/card-management/index',
        'pages/card-form/index',
        'pages/card-member-list/index',
        'pages/category-form/index',
        'pages/course-form/index',
        'pages/course-packages/index',
        'pages/package-form/index',
        'pages/lesson-form/index',
        'pages/lesson-edit/index',
        'pages/lesson-supplement/index',
        'pages/lesson-detail/index',
        'pages/schedule-form/index',
        'pages/booking-rule/index',
        'pages/teacher-booking-config/index',
        'pages/booking-record-detail/index',
        'pages/batch-reschedule-select/index',
        'pages/batch-reschedule-confirm/index',
        'pages/records/index',
        'pages/recharge-records/index',
        'pages/leave-request/index',
      ],
    },
    {
      root: 'package-settings',
      pages: [
        'pages/campus-settings/index',
        'pages/campus-settings/sub-campus',
        'pages/campus-settings/pay-day',
        'pages/campus-settings/holidays',
        'pages/campus-settings/subjects',
        'pages/campus-settings/notify',
        'pages/campus-settings/campus-data/index',
        'pages/campus-detail/index',
        'pages/venue-list/index',
        'pages/venue-form/index',
        'pages/room-form/index',
        'pages/system-settings/index',
        'pages/theme-settings/index',
        'pages/feedback/index',
        'pages/help/index',
        'pages/notification-send/index',
      ],
    },
    {
      root: 'package-statistics',
      pages: ['pages/alert-detail/index'],
    },
    {
      root: 'package-lead',
      pages: [
        'pages/my-invite/index',
        'pages/lead-form/index',
        'pages/lead-detail/index',
        'pages/trial-booking/index',
        'pages/proxy-booking-form/index',
        'pages/proxy-member-select/index',
        'pages/trial-slots/index',
        'pages/trial-slot-config/index',
        'pages/lead-booking-detail/index',
        'pages/lead-booking-edit/index',
        'pages/open-slot-edit/index',
        'pages/class-slot-config/index',
        'pages/invite-qrcode/index',
        'pages/invite-landing/index',
      ],
    },
  ],
  /** 隐私受限接口声明（微信隐私合规强制要求，未声明会 101 失败） */
  requiredPrivateInfos: ['chooseLocation'],
  /**
   * 隐私授权检查开关。
   * - true：chooseMedia / chooseLocation 等隐私接口在用户未同意隐私协议前会被微信直接拦截。
   * - 当前临时关闭（false）：公众平台《个人信息保护指引》还在配置中未发布生效，
   *   开启会导致真机选图/定位等接口被拦截且弹窗不弹出。待隐私指引审核发布生效后改回 true。
   */
  __usePrivacyCheck__: false,
  /** 进入课表页后预下载 package-lead 分包，加速「排课/预约」Tab 切换 */
  preloadRule: {
    'pages/schedule/index': {
      packages: ['package-lead'],
      network: 'all',
    },
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#3B6EF5',
    navigationBarTitleText: '松果排课',
    navigationBarTextStyle: 'white',
  },
  tabBar: {
    color: '#999999',
    selectedColor: '#3B6EF5',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
        iconPath: 'assets/icons/home_unselected.png',
        selectedIconPath: 'assets/icons/home_selected.png',
      },
      {
        pagePath: 'pages/schedule/index',
        text: '课表',
        iconPath: 'assets/icons/schedule_unselected.png',
        selectedIconPath: 'assets/icons/schedule_selected.png',
      },
      {
        pagePath: 'pages/statistics/index',
        text: '数据',
        iconPath: 'assets/icons/checkin_unselected.png',
        selectedIconPath: 'assets/icons/checkin_selected.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/icons/profile_unselected.png',
        selectedIconPath: 'assets/icons/profile_selected.png',
      },
    ],
  },
});
