export default defineAppConfig({
  /** 按需注入：仅加载当前页面声明的自定义组件，降低启动耗时与内存占用 */
  lazyCodeLoading: 'requiredComponents',
  pages: [
    'pages/home/index',
    'pages/schedule/index',
    'pages/statistics/index',
    'pages/profile/index',
  ],
  subPackages: [
    {
      root: 'package-auth',
      pages: [
        'pages/index/index',
        'pages/login/index',
        'pages/login/forgot-account/index',
        'pages/login/forgot-password/index',
        'pages/login/contact-support/index',
        'pages/register/index',
        'pages/register/role-select',
        'pages/register/role-info',
        'pages/profile-setup/index',
        'pages/onboarding/index',
        'pages/identity-select/index',
        'pages/parent-onboarding/index',
        'pages/role-switch/index',
        'pages/role-switch/add-role',
      ],
    },
    {
      root: 'package-student',
      pages: [
        'pages/students/index',
        'pages/student-detail/index',
        'pages/student-form/index',
        'pages/student-transfer/index',
        'pages/parent-bind/index',
        'pages/member-card-issue/index',
        'pages/member-card-detail/index',
        'pages/member-card-edit/index',
        'pages/follow-record-form/index',
        'pages/help/index',
        'pages/child-detail/index',
        'pages/children/index',
        'pages/profile-edit/index',
        'pages/attendance-anomaly/index',
        'pages/renewal-reminder/index',
      ],
    },
    {
      root: 'package-teacher',
      pages: [
        'pages/teacher-list/index',
        'pages/teacher-form/index',
        'pages/teacher-detail/index',
        'pages/salary-detail/index',
        'pages/salary-adjust/index',
        'pages/attendance/index',
        'pages/salary-home/index',
        'pages/salary-payment/index',
        'pages/salary-settings/index',
        'pages/salary-form/index',
        'pages/salary-template/index',
        'pages/salary-template-form/index',
        'pages/monthly-flow/index',
        'pages/staff-invite/index',
      ],
    },
    {
      root: 'package-course',
      pages: [
        'pages/booking/index',
        'pages/my-course/index',
        'pages/venue-booking/index',
        'pages/course-management/index',
        'pages/subject-management/index',
        'pages/subject-form/index',
        'pages/card-management/index',
        'pages/card-form/index',
        'pages/card-member-list/index',
        'pages/category-form/index',
        'pages/course-form/index',
        'pages/package-form/index',
        'pages/lesson-form/index',
        'pages/lesson-supplement/index',
        'pages/lesson-detail/index',
        'pages/schedule-form/index',
        'pages/booking-rule/index',
        'pages/teacher-booking-config/index',
        'pages/booking-record-detail/index',
        'pages/batch-reschedule-select/index',
        'pages/batch-reschedule-confirm/index',
        'pages/records/index',
        'pages/recharge-records/index',
        'pages/leave-request/index',
        'pages/parent-lesson-notes/index',
      ],
    },
    {
      root: 'package-settings',
      pages: [
        'pages/campus-settings/index',
        'pages/campus-settings/sub-campus',
        'pages/campus-settings/pay-day',
        'pages/campus-settings/holidays',
        'pages/campus-settings/subjects',
        'pages/campus-settings/notify',
        'pages/campus-settings/campus-data/index',
        'pages/campus-detail/index',
        'pages/venue-list/index',
        'pages/venue-form/index',
        'pages/room-form/index',
        'pages/system-settings/index',
        'pages/developer-mode/index',
        'pages/permission-settings/index',
        'pages/permission-form/index',
        'pages/threshold-config/index',
        'pages/todo-settings/index',
        'pages/my-todos/index',
        'pages/todo-collaborator/index',
        'pages/audit-log/index',
        'pages/theme-settings/index',
        'pages/feedback/index',
        'pages/help/index',
        'pages/notification-send/index',
        'pages/agreement/index',
        'pages/about/index',
        'pages/membership/index',
        'pages/store-entry/index',
        'pages/store-entry/pending/index',
        'pages/notifications/index',
        'pages/message-auth/index',
      ],
    },
    {
      root: 'package-statistics',
      pages: [
        'pages/alert-detail/index',
        'pages/finance-data/index',
        'pages/member-data/index',
        'pages/card-data/index',
        'pages/salary-data/index',
        'pages/record-transaction/index',
      ],
    },
    {
      root: 'package-lead',
      pages: [
        'pages/my-invite/index',
        'pages/trial-records/index',
        'pages/lead-form/index',
        'pages/lead-detail/index',
        'pages/trial-booking/index',
        'pages/proxy-booking-form/index',
        'pages/proxy-member-select/index',
        'pages/trial-slots/index',
        'pages/trial-slot-config/index',
        'pages/lead-booking-detail/index',
        'pages/lead-booking-edit/index',
        'pages/open-slot-edit/index',
        'pages/class-slot-config/index',
        'pages/invite-qrcode/index',
        'pages/invite-landing/index',
      ],
    },
  ],
  /** 隐私受限接口声明（微信隐私合规强制要求，未声明会 101 失败） */
  requiredPrivateInfos: ['chooseLocation'],
  /**
   * 隐私授权检查开关。
   * - true：chooseMedia / chooseLocation 等隐私接口在用户未同意隐私协议前会被微信直接拦截。
   * - 当前临时关闭（false）：公众平台《个人信息保护指引》还在配置中未发布生效，
   *   开启会导致真机选图/定位等接口被拦截且弹窗不弹出。待隐私指引审核发布生效后改回 true。
   */
  __usePrivacyCheck__: false,
  /** 进入课表页后预下载 package-lead、package-course 分包，加速预约相关跳转 */
  preloadRule: {
    'pages/schedule/index': {
      packages: ['package-lead', 'package-course'],
      network: 'all',
    },
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#3B6EF5',
    navigationBarTitleText: '松果排课',
    navigationBarTextStyle: 'white',
  },
  tabBar: {
    custom: true,
    color: '#999999',
    selectedColor: '#3B6EF5',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
        iconPath: 'assets/icons/home_unselected.png',
        selectedIconPath: 'assets/icons/home_selected.png',
      },
      {
        pagePath: 'pages/schedule/index',
        text: '课表',
        iconPath: 'assets/icons/schedule_unselected.png',
        selectedIconPath: 'assets/icons/schedule_selected.png',
      },
      {
        pagePath: 'pages/statistics/index',
        text: '数据',
        iconPath: 'assets/icons/checkin_unselected.png',
        selectedIconPath: 'assets/icons/checkin_selected.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/icons/profile_unselected.png',
        selectedIconPath: 'assets/icons/profile_selected.png',
      },
    ],
  },
});
